<!DOCTYPE html>
<html lang="en">
    <head>

        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">



        <script src="/components/jquery/jquery.min.js"></script>
        <link href="/components/bootstrap/css/bootstrap.min.css" rel="stylesheet">
        <script src="/components/bootstrap/js/bootstrap.min.js"></script>
        
        <script src="https://code.angularjs.org/1.4.2/angular.min.js"></script>
        <script src="https://code.angularjs.org/1.4.2/angular-route.min.js"></script>
        <script src="https://code.angularjs.org/1.4.2/angular-sanitize.min.js"></script>
              
        <script src="https://cdnjs.cloudflare.com/ajax/libs/tv4/1.2.7/tv4.min.js"></script>
        <script src="js/objectpath/lib/objectpath.js"></script>
               
        <script src="/js/angular-schema-form.min.js"></script>
        <script src="/js/angular-schema-form-bootstrap.min.js"></script>
       
        

        <?php echo $this->headScript(); ?>
        <?php echo $this->headLink(); ?>

       



        <title>Orinoco River Zend Framework demo site</title>
      
    </head>
    <body>
        <div class="container">
            <div class="header clearfix">
             


            </div>

            <br /><br />


            <?php echo $this->content; ?>


        </div>
    </body>
</html>
