<!DOCTYPE html>
<html lang="en">
    <head>

        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <?php echo $this->headScript(); ?>
        <?php echo $this->headLink(); ?>





        <title>Orinoco River Zend Framework demo site</title>

    </head>
    <body>
        <div class="container">
            <div class="header clearfix">



            </div>

            <br /><br />


            <?php echo $this->content; ?>


        </div>
    </body>
</html>
